spring.application.name=demo
# Usar variables de entorno para la BD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# El puerto ya está bien configurado para la nube
server.port=${PORT:8500}

# Email (Usar variables para seguridad)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Stripe (Usar variables)
pasarela.stripe.secret-key=${STRIPE_SECRET_KEY}
pasarela.stripe.public-key=${STRIPE_PUBLIC_KEY}

# Configuración JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=${JWT_EXPIRATION:18000000}

# Configuración CORS (Tu URL de Vercel)
cors.allowed-origins=${FRONTEND_URL}

# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# --- CONFIGURACIÓN DE LOGS ---

# Nivel General (Producción)
logging.level.root=INFO

# Para verificación y testing propio
logging.level.fullstack.demo=DEBUG

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n

# Guardar logs en archivo 
logging.file.name=logs/tienda-ropa.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7